[helpers]

[default]
depends = []

[default.variables]

[default.files]
"helix.toml" = "~/.config/helix/config.toml"
"kitty.conf" = "~/.config/kitty/kitty.conf"

[fish.files]
"fish/config.fish" = "~/.config/fish/config.fish"
"fish/functions/" = "~/.config/fish/functions/"

[mpv.files]
"mpv/mpv.conf" = "~/.config/mpv/mpv.conf"
"mpv/shaders" = "~/.config/mpv/shaders"

[settings]
default_target_type = "automatic"
