[helpers]

[default]
depends = []

[default.files]
"config.fish" = "~/.config/fish/config.fish"
"helix.toml" = "~/.config/helix/config.toml"
"kitty.conf" = "~/.config/kitty/kitty.conf"

[default.variables]

[settings]
default_target_type = "automatic"
